$().ready(function(){
        $.getJSON("/assets/races.json",function(data){
            console.log('success');
            $.each(data.races.race,function(i,race){
                $('#raceList').append('<h1>'+race.raceName+'</h1>');
		$('#raceList').append('<p>'+race.raceDetails+'</p>');
            });
        }).error(function(){
            console.log('error');
        });
    });
